--- 
  :log_dir: /var/log/kafo
  :log_name: configuration.log
  :log_level: info
  :no_prefix: false
  :mapping: {}
  :answer_file: "./config/answers.yaml"
  :installer_dir: "."
  :modules_dir: "./modules"
  :default_values_dir: /tmp
  :colors: true
  :color_of_background: :dark
  :hook_dirs: []
  :custom: {}
  :low_priority_modules: []
  :password: WwKIsi30Gu_x3LgR78IQRjkqO40vX-n7ycF9TLZLThk